### ISSUE TITLE
Possible improvements on README

### ISSUE THREAD

**Issue by chentong319** [pragnyan948/HISIM#1]
Perhaps, I am the first outside user of this project. Some initial feedback:

Suggest to put a concrete example for new user to start with in README.md, a command line with inputs. I just modified the first command line in README to `python3 analy_model.py --chip_architect M2D --N_tile 2  --ai_model Module_AI_Map/AI_Networks/DenseNet/NetWork_denseNet100.csv --thermal`
I got the following error message:
```
start HISIM simulation  

Traceback (most recent call last):
  File "/Users/chentong/Projects/HISIM/analy_model.py", line 140, in <module>
    network_params=load_ai_network(aimodel)                 #Load AI network parameters from the network csv file
  File "/Users/chentong/Projects/HISIM/Module_AI_Map/util_chip/util_mapping.py", line 27, in load_ai_network
    return network_params
UnboundLocalError: local variable 'network_params' referenced before assignment
```
I guess I just missed some parameters for analysis_model.py.

Another piece of suggestion for whole repository:  you may change your top directories into "docs, src, tests" to separate the documents, code for the simulator, and the inputs/outputs of the simulator run.

**Comment by pragnyan948** [comment]
Hey Chen,

Thank you for your comments and suggestions. 
Please use the command "python3 analy_model.py --chip_architect M2D --N_tile 2  --ai_model densenet121 --thermal".

The argument for "ai_model" can be chosen from below variables:
"AI models: vit, gcn, resnet50, resnet110, vgg16, densenet121"

I have also updated the Readme file accordingly.

Regards,
Pragnya

**Comment by chentong319** [comment]
Thanks for quick response. I got the following output:
```
start HISIM simulation  

---------------------------------------------------- 

start mapping  densenet121 

Alert!!! No available tile/tiers
please increase Tiers/tile number
```
I try N_tile 32 and got the same error.

**Comment by pragnyan948** [comment]
Hey Chen,

Please use N_tile as 100

Regards,
Pragnya
